global using static System.MathF;
global using static GameServerCore.Content.HashFunctions;
global using static LeagueSandbox.GameServer.API.ApiGameEvents;
global using static LeagueSandbox.GameServer.API.ApiEventManager;
global using static LeagueSandbox.GameServer.API.ApiFunctionManager;
global using static LeagueSandbox.GameServer.API.ApiMapFunctionManager;
global using Buffs;
global using System;
global using System.Linq;
global using GameServerCore;
global using System.Numerics;
global using GameServerCore.Enums;
global using System.Collections.Generic;
global using LeagueSandbox.GameServer.API;
global using GameServerCore.Scripting.CSharp;
global using LeagueSandbox.GameServer.GameObjects;
global using LeagueSandbox.GameServer.Scripting.CSharp;
global using LeagueSandbox.GameServer.GameObjects.StatsNS;
global using LeagueSandbox.GameServer.GameObjects.SpellNS;
global using LeagueSandbox.GameServer.GameObjects.SpellNS.Sector;
global using LeagueSandbox.GameServer.GameObjects.SpellNS.Missile;
global using LeagueSandbox.GameServer.GameObjects.AttackableUnits;
global using LeagueSandbox.GameServer.GameObjects.AttackableUnits.AI;
global using LeagueSandbox.GameServer.GameObjects.AttackableUnits.Buildings;
global using LeagueSandbox.GameServer.GameObjects.AttackableUnits.Buildings.AnimatedBuildings;